### ISSUE TITLE
Keyboard Shortcuts menu has white font on white background.

### ISSUE THREAD

**Issue by cy-james-lee** [lusignan/Nautical-Twilight#2]
I love the theme but some options have white font color on white background.

![image](https://user-images.githubusercontent.com/13931593/95204511-346c0680-07b2-11eb-9aba-0c2f2a1cec96.png)

**Comment by lusignan** [comment]
Thanks for catching that. I've recolored it so it's more cohesive.

**Comment by leungi** [comment]
@lusignan : facing similar issue, using the latest commit.

Also seeing this issue, which may be related.

![white-white](https://user-images.githubusercontent.com/30273868/97063515-bb1c3400-1565-11eb-9207-ae5576826565.png)
