### ISSUE TITLE
White on white background in keyboard shortcuts and global options panes

### ISSUE THREAD

**Issue by leungi** [lusignan/Nautical-Twilight#3]
@lusignan : 🙏 for this wonderful theme! It's the first dark theme that is not too dark that `tibble` console messages are camouflaged in background.

I'm using the latest commit, and facing similar issue as #2 .

Also seeing this issue, which may be related.

![image](https://user-images.githubusercontent.com/30273868/97096569-0a309a80-1634-11eb-86b7-47b1ff2fe1bd.png)

**Comment by canholyavkin** [comment]
Same here. (RStudio v1.4)

**Comment by leungi** [comment]
RStudio V1.4x as well; maybe that's the root cause.

**Comment by lusignan** [comment]
The issue isn't appearing in RStudio 1.3 which is the latest stable release and what I built it for. I'm not upgrading to 1.4 until it's officially released but once it is I'm aiming to change the ace code the same week.

**Comment by leungi** [comment]
@lusignan: I'll close this, as per your note.

Thanks again for the 🤩 artwork.

**Comment by canholyavkin** [comment]
Hello again. The RStudio officially upgraded to 1.4.
